;; Nukefile for AmaZone

;; source files
(set @nu_files 	  (filelist "nu/.*\.nu$"))
(set @resources   (filelist "^English\.lproj/Infoplist.strings$"))
(set @nib_files   (filelist "^English\.lproj/[^/]*\.nib$"))

;; application description
(set @application "RandomApp")
(set @application_identifier   "nu.programming.randomapp")

;; build tasks
(application-tasks)
(task "default" => "application")
