;; Nukefile for SpeakLine

;; source files
(set @nu_files 	  (filelist "nu/.*\.nu$"))
(set @resources   (filelist "^English\.lproj/Infoplist.strings$"))
(set @nib_files   (filelist "^English\.lproj/[^/]*\.nib$"))

;; application description
(set @application "SpeakLine")
(set @application_identifier   "nu.programming.speakline")

;; build tasks
(application-tasks)
(task "default" => "application")
